
ROWS, COLS = 45, 100
GRID = 3
CELL_W = COLS // GRID
CELL_H = ROWS // GRID
PROB_ROOM = 0.75
MIN_W, MAX_W = 4, 16
MIN_H, MAX_H = 3, 12
PAD = 2
MIN_ROOMS_COUNT = 4
MAX_LEVELS = 21
MAX_BACKPACK_ITEMS_PER_TYPE = 9
ELIXIR_DURATION = 20

SYM_EMPTY = " "
SYM_WALL = "#"
SYM_ROOM_FLOOR = "."
SYM_CORRIDOR = "*"
SYM_DOOR = "|"
SYM_PLAYER = "@"
SYM_EXIT = "E"
SYM_ITEM = "I"

WALKABLE_SYMBOLS = {
    SYM_ROOM_FLOOR,
    SYM_CORRIDOR,
    SYM_DOOR,
    SYM_EXIT,
    SYM_ITEM,
}

DEFAULT_MAX_HEALTH = 500
DEFAULT_AGILITY = 70
DEFAULT_STRENGTH = 70
DEFAULT_WEAPON = None
DEFAULT_TREASURES = 0

PERCENTS_UPDATE_DIFFICULTY_MONSTERS = 2

LOW_HOSTILITY_RADIUS = 2
AVERAGE_HOSTILITY_RADIUS = 4
HIGH_HOSTILITY_RADIUS = 6

INITIAL_HIT_CHANCE = 70
STANDART_AGILITY = 50
AGILITY_FACTOR = 0.3
INITIAL_DAMAGE = 30
STANDART_STRENGTH = 50
STRENGTH_FACTOR = 0.3
STRENGTH_ADDITION = 65
MAX_HP_PART = 10
SLEEP_CHANCE = 15
CHANCE_GHOST_VISIBLE = 20

MAX_MONSTERS_PER_ROOM = 2
MAX_CONSUMABLES_PER_ROOM = 3
LEVEL_UPDATE_DIFFICULTY = 10
OGRE_STEP = 2

SYM_ZOMBIE = 'z'
SYM_VAMPIRE = 'v'
SYM_GHOST = 'g'
SYM_OGRE = 'O'
SYM_SNAKE = 's'

PLAYER_NAME = "Juggernaut"

# Отображаемые имена врагов (Dota-inspired); ключи — OpponentType.name.
OPPONENT_DISPLAY_NAMES = {
    "ZOMBIE": "Dire Ghoul",
    "VAMPIRE": "Bloodseeker",
    "GHOST": "Skeleton Ghost",
    "OGRE": "Ogre Magi",
    "SNAKE": "Skywrath Mage",
}


def opponent_display_name(opponent_type):
    """Имя врага для сообщений и UI."""
    return OPPONENT_DISPLAY_NAMES.get(opponent_type.name, opponent_type.name.title())
