from domain.consts import COLS, ROWS

TILE_SIZE = 14
GRID_W = COLS * TILE_SIZE
GRID_H = ROWS * TILE_SIZE
PANEL_H = 90
SCREEN_W = GRID_W
SCREEN_H = GRID_H + PANEL_H
FPS = 30
WINDOW_TITLE = "Rogue 2.0"
